apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-multi-tenant-proxy-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-multi-tenant-proxy-server.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
  {{- .Values.config.data | nindent 4 }}
