apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-multi-tenant-proxy-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-multi-tenant-proxy-server.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-multi-tenant-proxy-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prometheus-multi-tenant-proxy-server.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          {{- if .Values.deployment.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              {{- with .Values.deployment.healthcheck.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              {{- with .Values.deployment.healthcheck.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.deployment.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/config
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "prometheus-multi-tenant-proxy-server.fullname" . }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
