apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-multi-tenant-proxy-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-multi-tenant-proxy-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "prometheus-multi-tenant-proxy-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9999
      protocol: TCP
